### ISSUE TITLE
Empty page

### ISSUE THREAD

**Issue by GinoGiotto** [tirix/metamath-web#17]
Mentioned in #10

>> http://metamath.tirix.org/mpeuni/toc?ref=61 This webpage is empty, maybe it doesn't render tables?
> 
> It does not even display any "chapter comment" at all. That's a new feature to be added. With the last version of metamath-knife, it should be easy.

**Comment by tirix** [comment]
With #20 and #22, header comments are supported, so pages like http://metamath.tirix.org/mpests/toc?ref=176 (ZF (ZERMELO-FRAENKEL) SET THEORY) now show the header's comment correctly. That was not the case before, so there is a real improvement.

However for the page http://metamath.tirix.org/mpeuni/toc?ref=61 it's a special case, the chapter in the source file seems to be genuinely empty, with the next chapter at the same level following immediately, without any content. In that case, it's rather `set.mm` which has to be fixed!

**Comment by GinoGiotto** [comment]
> the chapter in the source file seems to be genuinely empty

Good catch, I made a PR on set.mm with the fix https://github.com/metamath/set.mm/pull/3602

**Comment by GinoGiotto** [comment]
I'm closing this issue since this is a set.mm problem, not a metamath-web one.
