### ISSUE TITLE
Website doesn't work

### ISSUE THREAD

**Issue by GinoGiotto** [tirix/metamath-web#34]
At first I thought it was temporary, but it has been a few days now since the website produces a 503 error:

![website](https://github.com/tirix/metamath-web/assets/73717712/5f68aa33-917b-44d6-b2c1-ee648034fb99)

Any link will produce this error. Here is one as example: https://metamath.tirix.org/mpests/df-clel.html

**Comment by tirix** [comment]
Sorry I'm checking GitHub more rarely recently.
I tried following that link just now and it worked.
Do you still have the issue?

**Comment by GinoGiotto** [comment]
> I tried following that link just now and it worked. Do you still have the issue?

It works now.
