### ISSUE TITLE
Transition to https

### ISSUE THREAD

**Issue by GinoGiotto** [tirix/metamath-web#35]
The metamath-web pages used to be HTTPS, but for some reason, they have reverted to HTTP. I suggest switching them back to HTTPS.

Example: http://metamath.tirix.org/mpests/bezout.html

**Comment by GinoGiotto** [comment]
This is now fixed.

**Comment by tirix** [comment]
Sorry I completely missed this issue.

The SSL certificate had expired (for a while, actually!). I not only renewed it, but also ensured that it will automatically renew in the future.
