### ISSUE TITLE
Overlapping text among navigation buttons

### ISSUE THREAD

**Issue by tirix** [tirix/metamath-web#9]
@benjub sees [overlapping text among navigation buttons in the upper-right corner](https://github.com/tirix/metamath-web/pull/8#issuecomment-1019920898).

**Comment by tirix** [comment]
Here is what I see. Where do you see the overlap? Which browser/screen size do you use?
![image](https://user-images.githubusercontent.com/5831830/150771733-cb5e6aa6-b57b-48b9-becc-fcb28a0e320a.png)

**Comment by benjub** [comment]
Firefox, 100% zoom, large screen. For http://metamath.tirix.org:3030/mpests/toc?ref=63:

![overlap](https://user-images.githubusercontent.com/41090811/150772187-0e117d92-3d59-4e85-a0ff-5d9b26f98dc1.png)

**Comment by benjub** [comment]
For http://metamath.tirix.org:3030/mpests/idi :

![overlap2](https://user-images.githubusercontent.com/41090811/150772558-aee23e76-d53e-4045-a1e1-ab033370d041.png)

**Comment by tirix** [comment]
Thank you Benoît!

I just looks like the new styling for navigation has not been loaded.
Forcing the browser to fully reload using [CTRL+Shift+R](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_navigation) should do the trick.

**Comment by benjub** [comment]
This works. (I thought I had refreshed, but apparently not, sorry!).

**Comment by tirix** [comment]
No problem! You had the honour of opening the first issue in this repo ;)
I'll try to look into your other points, too.
